---
title: Umbrella
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  roles:
    title: Roles
    output: true
  undercover:
    title: Undercover
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: projects
  values:
    Project Images:
    - Image: 
    Services:
    - Service Type: 
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
